# TEXT SUMMARIZATION USING BART TRANSFORMER MODEL

In [ ]:
!pip install rouge-score bert-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.9.0+cu126)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.57.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.5.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.36.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.2.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2025.11.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=3.0.0->bert-score) (1.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.5 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=a3d5a232b41f53b7da46fbe49f9dee16f421f2779c76c0a0c9c49bc5634f1682
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, bert-score
Successfully installed bert-score-0.3.13 rouge-score-0.1.2

BART

- 1. WITHOUT FINE TUNING
- 2. WITH FINE - TUNING

#### LOADING THE DATASET

In [ ]:
import os
import torch
from rouge_score import rouge_scorer
from bert_score import score
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/DS310/Project/Dataset/merged_data/"

Mounted at /content/drive

In [ ]:
train_df = pd.read_csv(folder_path + "train.csv")
val_df = pd.read_csv(folder_path + "val.csv")
test_df = pd.read_csv(folder_path + "test.csv")

In [ ]:
test_df

,title,link,date_posted,headline,source,abstract,full_story,category
0,Why Some People Age Faster. And the 400 Genes ...,https://www.sciencedaily.com/releases/2025/08/...,"August 22, 2025",Why some people age faster. And the 400 genes ...,University of Colorado at Boulder,Researchers identified over 400 genes tied to ...,Scientists have uncovered more than 400 genes ...,health_medicine
1,Scientists Uncover a Multibillion-Year Epic Wr...,https://www.sciencedaily.com/releases/2024/05/...,"May 31, 2024",Scientists uncover a multibillion-year epic wr...,Tokyo Institute of Technology,Life evolved from simple geochemical processes...,The origin of life on Earth has long been a my...,fossils_ruins
2,Marfan Syndrome Increases Risk of Brain Altera...,https://www.sciencedaily.com/releases/2025/05/...,"May 16, 2025",Marfan syndrome increases risk of brain altera...,Universitat Autonoma de Barcelona,A study reveals that inflammation associated w...,A study by the Institut de Neurociències of th...,mind_brain
3,Telemedicine May Help Reduce Use of Unnecessar...,https://www.sciencedaily.com/releases/2025/02/...,"February 24, 2025",Telemedicine may help reduce use of unnecessar...,Mass General Brigham,A research team has found that telemedicine ma...,Low-value care -- medical tests and procedures...,science_society
4,"Lasers Just Unlocked a Hidden Side of Gold, Co...",https://www.sciencedaily.com/releases/2025/07/...,"July 19, 2025","Lasers just unlocked a hidden side of gold, co...",The Hebrew University of Jerusalem,Scientists have cracked a century-old physics ...,"Using only a blue laser and smart modulation, ...",matter_energy
...,...,...,...,...,...,...,...,...
1227,Simple Amino Acid Supplement Greatly Reduces A...,https://www.sciencedaily.com/releases/2025/11/...,"November 21, 2025",Simple amino acid supplement greatly reduces A...,Kindai University,Researchers discovered that the common amino a...,"New research reveals that arginine—a safe, ine...",mind_brain
1228,NaN,https://www.sciencedaily.com/releases/2025/09/...,"September 29, 2025",Black hole discovery confirms Einstein and Haw...,Simons Foundation,A fresh black hole merger detection has offere...,"When two black holes collide and merge, they r...",space_time
1229,Federal Subsidies for US Commercial Fisheries ...,https://www.sciencedaily.com/releases/2019/04/...,"April 5, 2019",Federal subsidies for US commercial fisheries ...,Duke University,A pending rule change proposed by the US Natio...,"In late 2018, the U.S. National Marine Fisheri...",business_industry
1230,Breakthrough Brain Discovery Reveals a Natural...,https://www.sciencedaily.com/releases/2025/11/...,"November 4, 2025",Breakthrough brain discovery reveals a natural...,University of Sydney,"Using powerful 7-Tesla brain imaging, research...",University of Sydney scientists have identifie...,health_medicine
1231,Scientists Just Took a Big Step Toward the Qua...,https://www.sciencedaily.com/releases/2025/06/...,"June 12, 2025",Scientists just took a big step toward the qua...,Helmholtz-Zentrum Dresden-Rossendorf,A team of Danish and German scientists has lau...,A focused ion beam (top) delivers individual E...,computer_math

In [ ]:
test_df['full_story'][0]

'Scientists have uncovered more than 400 genes linked to different forms of unhealthy aging, shedding light on why some people thrive into their 90s while others struggle decades earlier. Credit: Shutterstock\n\nIt\'s a fact of life: Some people age better than others.\nSome ease into their 90s with mind and body intact, while others battle diabetes, Alzheimer\'s or mobility issues decades earlier. Some can withstand a bad fall or bout of the flu with ease, while others never leave the hospital again.\nNew University of Colorado Boulder-led research, published this month in the journal Nature Genetics, sheds light on why that is.\nIn it, an international team of co-authors identify more than 400 genes associated with accelerated aging across seven different sub-types. The study reveals that different groups of genes underlie different kinds of disordered aging, a.k.a. frailty, ranging from cognitive decline to mobility issues to social isolation.\nThe findings lend support to what is known as the "geroscience hypothesis" -- the idea that to treat the multiple chronic illnesses that come with aging, we must treat aging itself.\n"To be able to identify treatments to stop or reverse accelerated biological aging, you need to know what the underlying biology is," said Isabelle Foote, first author on the paper and a postdoctoral researcher at CU\'s Institute for Behavioral Genetics. "This is the largest study yet to use genetics to try to do that."\nRedefining \'frailty\'\nThe study centers around "frailty," a catch-all term for the "multisystem physiological decline" that often comes with aging.\nMore than 40% of U.S. adults over age 65 are considered frail.\nDoctors typically assess frailty using a 30- point index that measures things like walking speed, grip strength, number of diagnosed illnesses and amount of social activity. The problem, said Foote, is that two people can get the same high frailty score even though one is cognitively sharp but can\'t walk and another is in good physical health but has a poor memory.\nThis lack of distinction has made it hard for doctors to make recommendations and for scientists to pinpoint the underlying causes of unhealthy aging.\n"Aging is not just one thing. There are many ways to be frail," said Dr. Kenneth Rockwood, a leading expert in frailty, based at Dalhousie University in Nova Scotia, Canada and co-author on the study. "The question then becomes: What genes are involved?"\nTo find out, the team conducted a "genome-wide association study" analyzing DNA and health information from hundreds of thousands of participants in the UK Biobank and other public datasets to see which genes were associated with 30 frailty symptoms.\nThey identified 408 genes associated with accelerated aging/frailty, a significant increase from the 37 genes previously identified.\nSome genes, they found, were strongly linked to certain subtypes of unhealthy aging, including: "disability"; "poor cognition"; "metabolic problems"; "multiple diseases"; "generally unhealthy lifestyle"; and "limited social support."\nFor instance, the SP1 gene, associated with immune function and Alzheimer\'s disease was strongly associated with the broad "poor cognition" subtype, whereas the FTO gene, a gene known to be associated with obesity, seemed to underly several different categories of unhealthy aging.\n"What this paper does is not only identify sub-facets of disordered aging but also demonstrate that there is very different biology underlying them," said senior author Andrew Grotzinger, assistant professor of psychology and neuroscience at CU Boulder. "The tangible next step is to figure out how to treat this underlying biology."\nAn anti-aging pill?\nIn the near term, the authors suggest that clinical measurements of frailty -- which often shows up long before specific diseases -- be expanded to include the six subtypes.\nThat way, someone diagnosed as cognitively frail could be guided toward therapies to prevent dementia, while someone frail in the metabolic domain might take steps to prevent diabetes or heart disease.\nFoote envisions a day when people could get a "polygenic risk score" offering more detailed insight into what kind of unhealthy aging they are prone to.\nBut the holy grail, she says, would be to identify the molecular pathways that drive aging itself and develop therapies to put the brakes on.\nIs a single anti-aging pill on the horizon?\nNot likely.\nBut could there one day be a pill to treat a package of age-related metabolic issues, and another to address numerous cognitive issues?\nIt\'s a tantalizing idea, said Grotzinger.\n"This paper suggests that it\'s probably not going to be a single magic pill to address all the diseases that come with aging, but maybe it doesn\'t need to be hundreds anymore."'

In [ ]:
test_df['abstract'][0]

'Researchers identified over 400 genes tied to various forms of frailty, offering fresh insight into why people age differently. The study highlights six distinct pathways of unhealthy aging, opening the door to more precise, targeted anti-aging interventions.'

## 1. USING THE MODEL WITHOUT FINE TUNING

In [ ]:
from transformers import BartTokenizerFast, BartForConditionalGeneration

#### LOADING THE BART MODEL

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
tokenizer = BartTokenizerFast.from_pretrained("facebook/bart-base")
model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")
model.to(device)
model.eval()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50265, 768, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0-5): 6 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0-5): 6 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=768, out_features=50265, bias=False)
)

In [ ]:
article_1 = test_df['full_story'][0]

orig_len = len(article_1.split())
max_length = int(orig_len * 0.18)
min_length = int(max_length * 0.4)
max_length = min(max_length, 150)

In [ ]:
# Clean text
def clean_text(t):
    if not isinstance(t, str):
        return ""
    t = t.replace("\x00", "").replace("\ufffd", "")
    return t.strip()


# Auto-length calculation
def auto_length(text):
    orig_len = len(text.split())
    max_length = min(int(orig_len * 0.09), 150)
    min_length = int(max_length * 0.4)
    return max_length, min_length


#  Summarizer with batch
def summarize_batch_safe(texts, batch_size=2):
    summaries = []
    num_batches = (len(texts) + batch_size - 1) // batch_size

    for i in range(num_batches):
        batch_texts = texts[i*batch_size : (i+1)*batch_size]

        print(f"\n===== BATCH {i+1}/{num_batches} =====")
        print("Input size:", len(batch_texts))

        cleaned = [clean_text(t) for t in batch_texts]

        try:
            inputs = tokenizer(
                cleaned,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            ).to(device)
        except Exception as e:
            print("Tokenization failed:", e)
            summaries.extend([""] * len(cleaned))
            continue

        print("Max tokenized length:", inputs["input_ids"].shape[1])

        max_lens = [auto_length(t)[0] for t in cleaned]
        min_lens = [auto_length(t)[1] for t in cleaned]

        final_max_len = max(max_lens)
        final_min_len = min(min_lens)

        print("Generate max_length:", final_max_len)
        print("Generate min_length:", final_min_len)

        try:
            outputs = model.generate(
                **inputs,
                max_length=final_max_len,
                min_length=final_min_len,
                num_beams=4,
                no_repeat_ngram_size=3
            )
            batch_sum = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        except Exception as e:
            print("❌ Generation failed:", e)
            batch_sum = [""] * len(cleaned)

        for j, s in enumerate(batch_sum):
            print(f"\n--- Sample {j+1} ---")
            print(s[:300], "...")

        summaries.extend(batch_sum)

    return summaries


# Evaluation (ROUGE + BERTScore)
def evaluate_summaries(refs, preds):
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

    r1, r2, rl = [], [], []
    for ref, pred in zip(refs, preds):
        scores = scorer.score(ref, pred)
        r1.append(scores["rouge1"].fmeasure)
        r2.append(scores["rouge2"].fmeasure)
        rl.append(scores["rougeL"].fmeasure)

    # BERTScore
    P, R, F = score(preds, refs, lang="en")

    return {
        "ROUGE-1": 100 * sum(r1)/len(r1),
        "ROUGE-2": 100 * sum(r2)/len(r2),
        "ROUGE-L": 100 * sum(rl)/len(rl),
        "BERTScore": 100 * float(F.mean())
    }

test_texts = test_df["full_story"].astype(str).tolist()

test_df["bart_summary"] = summarize_batch_safe(
    test_texts,
    batch_size=2
)

Streaming output truncated to the last 5000 lines.
Generate max_length: 82
Generate min_length: 21

--- Sample 1 ---
Cause and effect. We understand this concept from an early age. Tug on a pull toy's string, and the toy follows. Naturally, things get much more complicated as a system grows, as the number of variables increases, and as noise enters the picture. Eventually, it can become almost impossible to tell w ...

--- Sample 2 ---
People consistently underestimate others' desire for constructive feedback and therefore don't provide it, even when it could improve another person's performance on a task, according to research published by the American Psychological Association."People often have opportunities to provide others w ...

===== BATCH 201/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 52
Generate min_length: 20

--- Sample 1 ---
Water molecules are a driving force in the formation of molecular bonds, for example in proteins. Credit: INT, KIT, Constructor University in Bremen/Handout via StoryfulWater is present almost everywhere. It covers most of our ...

--- Sample 2 ---
Children who grow up in disadvantaged neighborhoods -- areas with higher levels of crime and deprivation, and lower access to community resources -- are at risk of developing depression and new research led by faculty at Binghamton University, State University of New York, may ...

===== BATCH 202/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 84
Generate min_length: 18

--- Sample 1 ---
Scientists at Washington State University have found that juvenile European green crabs can do as much damage as adults to shellfish and native sea plants, calling into question current methods to eradicate the invasive crustaceans.Continue Reading BelowGreen crabs are a massive threat to Washington ...

--- Sample 2 ---
Concept design for a rectangular space telescope, modeled after the Diffractive Interfero Coronagraph Exoplanet Resolver (DICER), a notional infrared space observatory, and the James Webb Space Telescope. Credit: Leaf Swordy/Rensselaer Polytechnic Institute (RPI) The Earth supports the only known li ...

===== BATCH 203/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 89
Generate min_length: 31

--- Sample 1 ---
Playa del Carmen, a popular vacation destination on Mexico's Yucatán Peninsula, faces significant Sargassum strandings during summer months, as do other Caribbean coastlines. To maintain beach access for swimmers, the brown algae must be regularly cleared using machinery. Researchers at the Max Plan ...

--- Sample 2 ---
Minor everyday rises in blood pressure due to short-term stressors can be linked to a brain area that controls conscious and learned motor skills. This discovery, presented by University of Gothenburg researchers, paves the way for a better understanding of how micro-stress affects the brain and, in ...

===== BATCH 204/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 93
Generate min_length: 10

--- Sample 1 ---
In biology, enzymes have evolved over millions of years to drive chemical reactions. Scientists from the Max Planck Institute for Dynamics and Self-Organization (MPI-DS) now derived universal rules to enable the de novo design of optimal enzymes. As an example, they considered the enzymatic reaction ...

--- Sample 2 ---
A recently discovered solar system with six confirmed exoplanets and a possible seventh is boosting astronomers' knowledge of planet formation and evolution. Relying on a globe-spanning arsenal of observatories and instruments, a team led by researchers at the University of California, Irvine has co ...

===== BATCH 205/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 85
Generate min_length: 22

--- Sample 1 ---
Neural networks are one typical structure on which artificial intelligence can be based. The term ›neural‹ describes their learning ability, which to some extent mimics the functioning of neurons in our brains. To be able to work, several key ingredients are required: one of them is an activation fu ...

--- Sample 2 ---
A global survey shows strong public trust in scientists, but also a desire for more alignment between scientific priorities and everyday concerns like health, energy, and poverty, rather than defense. Most people want researchers to be more publicly engaged and responsive. Credit: Shutterstock A glo ...

===== BATCH 206/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 82
Generate min_length: 12

--- Sample 1 ---
FuZE-3’s plasma chamber is only about 12 feet long and produces hot dense plasma filaments a few millimeters wide. Credit: Zap Energy/Zap Energy, Inc. (www.zapenergy.com) Z-pinch Experiment 3 has reached a major milestone in the field of plasma physics. The team has produced plasma with electron pre ...

--- Sample 2 ---
Detecting infrared light is critical in an enormous range of technologies, from remote controls to autofocus systems to self-driving cars and virtual reality headsets. That means there would be major benefits from improving the efficiency of infrared sensors, such as photodiodes.Researchers at Aalto ...

===== BATCH 207/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 67
Generate min_length: 25

--- Sample 1 ---
High levels of nickel and urea once throttled early cyanobacteria, keeping Earth’s air oxygen-free. Their gradual decline unleashed an oxygen boom that transformed the planet and made complex life possible. Credit: Shutterstock The Great Oxidation Event (GOE)The arrival of oxygen in Earth's atmosphe ...

--- Sample 2 ---
Researchers have gained a new understanding of how the brain processes reward and risk information. A study by neuroscientists Raymundo Báez-Mendoza from the German Primate Center (DPZ) -- Leibniz Institute for Primate Research in Göttingen and Fabian Grabenhorst from ...

===== BATCH 208/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 31

--- Sample 1 ---
A team of scientists from Goethe University Frankfurt, University of Marburg and Stockholm University have elucidated an ancient mechanism of cellular respiration. To that end, they studied bacteria that feed on the gases carbon dioxide and hydrogen, and turn them into acetic acid -- a metabolic pat ...

--- Sample 2 ---
Sustainably produced, biodegradable materials are an important focus of modern materials science. However, when working natural materials such as cellulose, lignin or chitin, researchers face a trade-off. Although these substances are biodegrable in their pure form, they are often not ideal when it  ...

===== BATCH 209/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 132
Generate min_length: 17

--- Sample 1 ---
Clothes that can mimic the feeling of being touched, touch displays that provide haptic feedback to users, or even ultralight loudspeakers. These are just some of the devices made possible using thin silicone films that can be precisely controlled so that they vibrate, flex, press or pull exactly as ...

--- Sample 2 ---
Oceans are becoming a climate battleground, with fast-moving interventions like coral engineering and carbon capture. But without strong oversight and ethical guardrails, these efforts could backfire, researchers warn. Credit: Shutterstock.com Climate interventions are accelerating in our oceans - b ...

===== BATCH 210/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 46
Generate min_length: 13

--- Sample 1 ---
Companies should avoid scheduling important work tasks immediately following an election, according to a study from the University of Waterloo.Researchers discovered the outcome of a U.S. presidential election can affect employees' engagement and performance at work ...

--- Sample 2 ---
People are more comfortable talking to female rather than male robots working in service roles in hotels, according to a study by Washington State University researcher Soobin Seo.The study, which surveyed about 170 people on hypothetical service ...

===== BATCH 211/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 80
Generate min_length: 21

--- Sample 1 ---
A University of Liverpool study has used advanced genetic and genomic techniques to offer a major step forward in understanding and diagnosing infectious intestinal diseases.The large-scale study analysed more than 1,000 stool samples from people with diarrhoeal illness to harness two cutting edge t ...

--- Sample 2 ---
Friendship comes with complex pros and cons -- possibly explaining why some individuals are less sociable, according to a new study of gorillas.Scroll down for videoScientists examined over 20 years of data on 164 wild mountain gorillas, to see how their social lives affected their health.The findin ...

===== BATCH 212/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 63
Generate min_length: 24

--- Sample 1 ---
Josephson junction structures—quantum devices made of two superconductors and a thin non-superconducting barrier—using different forms of germanium (Ge): super-Ge (in gold), semiconducting Ge (in blue), and Super-Ge on wafer-level scale. ...

--- Sample 2 ---
Lifestyle and health factors that are linked with heart disease appear to have a greater impact on cardiovascular risk in women than men, according to a study being presented at the American College of Cardiology's Annual Scientific Session (ACC.25).While factors such as diet, exercise, smoking and  ...

===== BATCH 213/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 56
Generate min_length: 20

--- Sample 1 ---
Researchers have used the chemical fingerprints of zinc contained in meteorites to determine the origin of volatile elements on Earth. The results suggest that without 'unmelted' asteroids, there may not have been enough of these compounds on Earth for life to emerge.Volatiles ...

--- Sample 2 ---
Researchers report February 15 in the journal Cell that ancient viruses may be to thank for myelin -- and, by extension, our large, complex brains. The team found that a retrovirus-derived genetic element or "retrotransposon" is essential for ...

===== BATCH 214/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 70
Generate min_length: 23

--- Sample 1 ---
In the parable of the blind men and the elephant, several blind men each describe a different part of an elephant they are touching -- a sharp tusk, a flexible trunk, or a broad leg -- and disagree about the animal's true nature. The story illustrates the problem of understanding an unseen, or laten ...

--- Sample 2 ---
An artist's depiction of hair, made out of keratin, denaturing when ions are present. Credit: Michael Rosnach/Harvard John A. Paulson School of Engineering and Applied Sciences (SEAS)Key Takeaways From This New StudySEAS researchers have discovered the chemical mechanism by which certain salt compou ...

===== BATCH 215/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 37
Generate min_length: 9

--- Sample 1 ---
How do rogue planetary-mass objects -- celestial bodies with masses between stars and planets -- form? An international team of astronomers, including the University of Zurich, has used advanced ...

--- Sample 2 ---
People's preference for simple explanations of any situation is connected to their desire to execute tasks efficiently, finds a new study from the University of Waterloo."These findings show that ...

===== BATCH 216/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 114
Generate min_length: 38

--- Sample 1 ---
The dazzling “RBFLOAT” radio burst, originating nearby in the Ursa Major constellation, offers the clearest view yet of the environment around these mysterious flashes. Credit: Danielle Futselaar et al. A fast radio burst is an immense flash of radio emission that lasts for just a few milliseconds,  ...

--- Sample 2 ---
Bacteria can be engineered to sense a variety of molecules, such as pollutants or soil nutrients. In most cases, however, these signals can only be detected by looking at the cells under a microscope or similarly sensitive lab equipment, making them impractical for large-scale use. MIT researchers h ...

===== BATCH 217/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 72
Generate min_length: 16

--- Sample 1 ---
Boys are good at math, girls not so much? A study from the University of Zurich has analyzed the social mechanisms that contribute to the gender gap in math confidence. While peer comparisons seem to play a crucial role for boys, girls' subjective evaluations are more likely to be based on objective ...

--- Sample 2 ---
One nerve cell type (yellow) of several hundred that ETH researchers have grown from stem cells in the laboratory (microscopy image). Credit: Hsiu-Chuan Lin and Malgorzata Santel / ETH Zurich/Handout via StoryfulNerve cells are not just nerve cells. Depending on how finely we distinguish, there ...

===== BATCH 218/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 114
Generate min_length: 28

--- Sample 1 ---
In a groundbreaking discovery, researchers from Florida Atlantic University's Charles E. Schmidt College of Medicine have identified a never-before-seen mechanism that enables the human immunodeficiency type 1 virus (HIV-1) to evade the body's natural defenses and use it to support its survival and  ...

--- Sample 2 ---
Research led by climate scientists from the Vrije Universiteit Brussel (VUB) reveals that millions of today's young people will live through unprecedented lifetime exposure to heatwaves, crop failures, river floods, droughts, wildfires and tropical storms under current climate policies. If global te ...

===== BATCH 219/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 38
Generate min_length: 7

--- Sample 1 ---
Drastic declines in biodiversity due to human activities present risks to understanding animal behaviors such as tool use, according to researchers from the University of Victoria and the Max Planck Institute for ...

--- Sample 2 ---
Learning a language later in life changes how the two halves of the brain contribute. As skills improve, language comprehension changes hemisphere specialization, but production does not, according to new research ...

===== BATCH 220/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 61
Generate min_length: 22

--- Sample 1 ---
A longer paternity leave after the birth of a child can improve the co-parenting relationship between moms and dads in a key way, a new study finds.Researchers found that mothers were less likely to discourage fathers' involvement in parenting if the dads had taken more time off after their child wa ...

--- Sample 2 ---
Are we putting our faith in technology that we don't fully understand? A new study from the University of Surrey comes at a time when AI systems are making decisions impacting our daily lives -- from banking and healthcare to crime detection. The study calls for an immediate shift in how ...

===== BATCH 221/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 68
Generate min_length: 19

--- Sample 1 ---
Virtual reality nature experiences trigger the brain's natural painkillers, offering real relief for chronic-like pain. Credit: Shutterstock VR nature scenes help relieve pain in people living with long-term pain, researchers have found. (Image: Shutterstock)Immersing in virtual reality (VR) nature  ...

--- Sample 2 ---
Diamond quantum sensors can be used to analyze the magnetization response of soft magnetic materials used in power electronics; report scientists based on collaborative research. Using a novel imaging technique, they developed quantum protocols to simultaneously image both the amplitude and phase of ...

===== BATCH 222/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 22

--- Sample 1 ---
A new study from Cedars-Sinai examined whether a specialized diet could improve symptoms of gastrointestinal disorders linked to an imbalance in gut microbiota.The research tested the elemental diet's effectiveness and explored whether improving its unappealing taste -- a major barrier -- could help ...

--- Sample 2 ---
In the past two years, the Food and Drug Administration has approved two novel Alzheimer's therapies, based on data from clinical trials showing that both drugs slowed the progression of the disease. But while the approvals of lecanemab and donanemab, both antibody therapies that clear plaque-causin ...

===== BATCH 223/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 13

--- Sample 1 ---
Determining how strong your drink is doesn't need to be either guesswork or lab work. New research has made it as simple as checking your messages -- and more colorful, too. Credit: Osaka Metropolitan University Osaka-Osaka Metropolitan University researchers have developed a smartphone-compatible a ...

--- Sample 2 ---
A University at Buffalo researcher's recent work on dyslexia has unexpectedly produced a startling discovery which clearly demonstrates how the cooperative areas of the brain responsible for reading skill are also at work during apparently unrelated activities, such as multiplication.The findings, p ...

===== BATCH 224/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 50
Generate min_length: 16

--- Sample 1 ---
A research team at POSTECH (Pohang University of Science and Technology) has successfully developed a super-photostable organic dye after two years of dedicated research -- demonstrating perseverance akin to that of Marie Curie, who painstaking ...

--- Sample 2 ---
Scientists have discovered a new mechanism that acts via an immune cell and points toward a different way of treating chronic pain. Credit: UC San FranciscoFemale hormones can suppress pain by making immune cells near the spinal cord produce opioids, a new study ...

===== BATCH 225/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 79
Generate min_length: 16

--- Sample 1 ---
Researchers at the University of Minnesota have achieved a new material that will be pivotal in making the next generation of high-power electronics faster, transparent and more efficient. This artificially designed material allows electrons to move faster while remaining transparent to both visible ...

--- Sample 2 ---
Singing to your infant can significantly boost the baby's mood, according to a recent Yale study published May 28 in Child Development. (Yale University Press)Around the world and across cultures, singing to babies seems to come instinctively to caregivers. Now, new findings support that singing is  ...

===== BATCH 226/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 87
Generate min_length: 21

--- Sample 1 ---
Nearly 3 out of every 4 older Americans have experienced at least one extreme weather event in the last two years, a new University of Michigan poll finds. And living through such an event appears to make a big difference in how they view the potential impact of climate change on their health.The ne ...

--- Sample 2 ---
A new study from the University of Georgia College of Public Health found that about 6% of pregnant women reported using marijuana during the last month, and many did not associate it with health risks. The study highlights the importance of education surrounding marijuana use during pregnancy, said ...

===== BATCH 227/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 85
Generate min_length: 17

--- Sample 1 ---

In [ ]:
metrics = evaluate_summaries(
    refs=test_df["abstract"].astype(str).tolist(),
    preds=test_df["bart_summary"].tolist()
)

print("\n=========== FINAL METRICS ===========")
for k, v in metrics.items():
    print(f"{k}: {v:.4f}")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=========== FINAL METRICS ===========
ROUGE-1: 49.9512
ROUGE-2: 36.7351
ROUGE-L: 43.0527
BERTScore: 90.2855

In [ ]:
test_df["abstract"].apply(lambda x: len(x.split())).describe()

count    1232.000000
mean       49.444805
std        21.443449
min         9.000000
25%        33.000000
50%        47.000000
75%        64.000000
max       175.000000
Name: abstract, dtype: float64

In [ ]:
test_df["bart_summary"].apply(lambda x: len(x.split())).describe()

count    1232.000000
mean       56.115260
std        17.367618
min        20.000000
25%        43.000000
50%        54.000000
75%        66.000000
max       124.000000
Name: bart_summary, dtype: float64

## 2. FINE - TUNING MODEL

In [ ]:
!pip install transformers datasets sentencepiece evaluate rouge_score bert_score accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: bert_score in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.9.0+cu126)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (3.2.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.9 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import pandas as pd
from datasets import Dataset
from transformers import (
    BartTokenizerFast,
    BartForConditionalGeneration,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq,
)
import evaluate
import torch

In [ ]:
train_df = train_df[['full_story', 'abstract']]
val_df = val_df[['full_story', 'abstract']]
test_df = test_df[['full_story', 'abstract']]

train = Dataset.from_pandas(train_df)
val = Dataset.from_pandas(val_df)
test = Dataset.from_pandas(test_df)

In [ ]:
from transformers import BartTokenizerFast

tokenizer = BartTokenizerFast.from_pretrained("facebook/bart-base")

MAX_INPUT = 512
MAX_TARGET = 128

def preprocess(examples):
    # Encode input (full_story)
    model_inputs = tokenizer(
        examples["full_story"],
        max_length=MAX_INPUT,
        padding="max_length",
        truncation=True,
    )

    # Encode summary (abstract)
    labels = tokenizer(
        examples["abstract"],
        max_length=MAX_TARGET,
        padding="max_length",
        truncation=True,
    )

    # Replace padding token id with -100
    labels["input_ids"] = [
        [(lid if lid != tokenizer.pad_token_id else -100) for lid in label]
        for label in labels["input_ids"]
    ]

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

In [ ]:
train_tokenized = train.map(
    preprocess,
    batched=True,
    remove_columns=train.column_names
)

val_tokenized = val.map(
    preprocess,
    batched=True,
    remove_columns=val.column_names
)

test_tokenized = test.map(
    preprocess,
    batched=True,
    remove_columns=test.column_names
)

Map:   0%|          | 0/9848 [00:00<?, ? examples/s]

Map:   0%|          | 0/1231 [00:00<?, ? examples/s]

Map:   0%|          | 0/1232 [00:00<?, ? examples/s]

In [ ]:
model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")
model.to("cuda")

model.safetensors:   0%|          | 0.00/558M [00:00<?, ?B/s]

BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50265, 768, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0-5): 6 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0-5): 6 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=768, out_features=50265, bias=False)
)

In [ ]:
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="./bart_finetuned",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    num_train_epochs=3,
    fp16=True,
    logging_steps=50,
    save_steps=500,
    save_total_limit=2,
    report_to="none",
)

In [ ]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,
    data_collator=data_collator,
    tokenizer=tokenizer,
)

/tmp/ipython-input-2156707883.py:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(

TrainOutput(global_step=7386, training_loss=1.042325714755891, metrics={'train_runtime': 1930.0801, 'train_samples_per_second': 15.307, 'train_steps_per_second': 3.827, 'total_flos': 9007026961121280.0, 'train_loss': 1.042325714755891, 'epoch': 3.0})

In [ ]:
def auto_length(text):
    orig_len = len(text.split())
    max_length = min(int(orig_len * 0.09), 150)
    min_length = max(5, int(max_length * 0.4))
    return max_length, min_length

def summarize(text):
    max_l, min_l = auto_length(text)

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to("cuda")

    output = model.generate(
        **inputs,
        max_length=max_l,
        min_length=min_l,
        num_beams=4,
        no_repeat_ngram_size=3,
    )

    return tokenizer.decode(output[0], skip_special_tokens=True)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
model_path = "/content/drive/MyDrive/DS310/Project/checkpoint-7000-BART"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSeq2SeqLM.from_pretrained(model_path).to(device)

In [ ]:
def clean_text(t):
    if not isinstance(t, str):
        return ""
    t = t.replace("\x00", "").replace("\ufffd", "")
    return t.strip()

In [ ]:
def auto_length(text):
    orig_len = len(text.split())

    max_length = min(int(orig_len * 0.09), 150)
    max_length = max(max_length, 30)

    min_length = int(max_length * 0.35)
    min_length = min(min_length, max_length - 5)

    return max_length, min_length

In [ ]:
def summarize_batch_safe(texts, batch_size=2):
    summaries = []
    num_batches = (len(texts) + batch_size - 1) // batch_size

    for i in range(num_batches):
        batch_texts = texts[i*batch_size:(i+1)*batch_size]
        print(f"\n===== BATCH {i+1}/{num_batches} =====")
        print("Input size:", len(batch_texts))

        cleaned = [clean_text(t) for t in batch_texts]

        # Tokenize
        try:
            inputs = tokenizer(
                cleaned,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            ).to(device)
        except Exception as e:
            print("Tokenization failed:", e)
            summaries.extend([""] * len(cleaned))
            continue

        print("Max tokenized length:", inputs["input_ids"].shape[1])

        # Auto lengths
        max_lens = [auto_length(t)[0] for t in cleaned]
        min_lens = [auto_length(t)[1] for t in cleaned]

        final_max_len = min(max(max_lens), 150)
        final_min_len = max(min_lens)

        if final_min_len >= final_max_len:
            final_min_len = max(5, final_max_len - 10)

        print("Generate max_length:", final_max_len)
        print("Generate min_length:", final_min_len)

        # Generate
        try:
            outputs = model.generate(
                **inputs,
                max_length=final_max_len,
                min_length=final_min_len,
                num_beams=4,
                no_repeat_ngram_size=3
            )
            batch_sum = tokenizer.batch_decode(outputs, skip_special_tokens=True)
        except Exception as e:
            print("Generation failed:", e)
            batch_sum = [""] * len(cleaned)

        # Print
        for j, s in enumerate(batch_sum):
            print(f"\n--- Sample {j+1} ---")
            print(s[:300], "...")

        summaries.extend(batch_sum)

    return summaries

In [ ]:
def evaluate_summaries(refs, preds):
    scorer = rouge_scorer.RougeScorer(
        ["rouge1", "rouge2", "rougeL"],
        use_stemmer=True
    )

    r1 = []
    r2 = []
    rl = []

    for ref, pred in zip(refs, preds):
        scores = scorer.score(ref, pred)
        r1.append(scores["rouge1"].fmeasure)
        r2.append(scores["rouge2"].fmeasure)
        rl.append(scores["rougeL"].fmeasure)

    P, R, F = score(preds, refs, lang="en")

    return {
        "ROUGE-1": 100 * sum(r1) / len(r1),
        "ROUGE-2": 100 * sum(r2) / len(r2),
        "ROUGE-L": 100 * sum(rl) / len(rl),
        "BERTScore": 100 * float(F.mean())
    }

In [ ]:
test_texts = test_df["full_story"].astype(str).tolist()

test_df["fine_tune_bart_summary"] = summarize_batch_safe(
    test_texts,
    batch_size=2
)

Streaming output truncated to the last 5000 lines.
Generate max_length: 82
Generate min_length: 28

--- Sample 1 ---
A new mathematical tool can tease out the contributions that each variable in a system makes to a measured effect -- both separately and, more importantly, in combination. ...

--- Sample 2 ---
People consistently underestimate others' desire for constructive feedback and therefore don't provide it, even when it could improve another person's performance on a task, according to new research. ...

===== BATCH 201/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 52
Generate min_length: 18

--- Sample 1 ---
Water doesn’t just circulate freely—it actively binds molecules inside tiny molecular cavities. Scientists discovered that trapped water acts like a passive bystander, allowing molecules to bind more strongly. This “highly energetic” state explains why molecules ...

--- Sample 2 ---
Psychologists found that the brains of children from areas containing higher levels of deprivation show less response to reward and loss, but only if they were already at risk for depression based on a family history of the disorder. ...

===== BATCH 202/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 84
Generate min_length: 29

--- Sample 1 ---
Scientists have found that juvenile European green crabs can do as much damage as adults to shellfish and native sea plants, calling into question current methods to eradicate the invasive crustaceans. ...

--- Sample 2 ---
Astronomers are racing to find life on planets that support liquid water, but there’s a catch: the vastness of space makes it impossible to reach them. Using the James Webb Space Telescope, scientists are aiming to find the closest stars to the sun, where they’d need to collect enough light to separ ...

===== BATCH 203/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 89
Generate min_length: 31

--- Sample 1 ---
Sargassum’s relentless growth has alarmed Caribbean beachgoers, especially during the summer months. Researchers have discovered that strong winds and nitrogen capture phosphorus from the surface and transport it northward. This symbiotic relationship helps cyanobacteria convert the algae into nutri ...

--- Sample 2 ---
Minor everyday rises in blood pressure due to short-term stressors can be linked to a brain area that controls conscious and learned motor skills. This discovery paves the way for a chance to influence the rises in pressure and, in the long run, prevent hypertension. ...

===== BATCH 204/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 93
Generate min_length: 32

--- Sample 1 ---
In biology, enzymes have evolved over millions of years to drive chemical reactions. Scientists have now derived universal rules to enable the de novo design of optimal enzymes. As an example, they considered the enzymatic reaction of breaking a dimer into two monomer molecules. Considering the geom ...

--- Sample 2 ---
A recently discovered solar system with six confirmed exoplanets and a possible seventh is boosting astronomers' knowledge of planet formation and evolution. Relying on a globe-spanning arsenal of observatories and instruments, a team has compiled the most precise measurements yet of the exoplanetet ...

===== BATCH 205/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 85
Generate min_length: 29

--- Sample 1 ---
Neural networks are one typical structure on which artificial intelligence can be based. The term ›neural‹ describes their learning ability, which to some extent mimics the functioning of neurons in our brains. To be able to work, several key ingredients are required: one of them is an activation fu ...

--- Sample 2 ---
A massive post-pandemic survey across 68 countries reveals that trust in scientists is at a moderately high level worldwide, largely driven by strong public trust in science, societal expectations, and public views on research priorities. Countries like Germany, Spain, and Portugal show a clear link ...

===== BATCH 206/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 82
Generate min_length: 28

--- Sample 1 ---
Zap Energy’s new Fusion Z-pinch Experiment 3 has generated plasmas with electron pressures of up to 830 megapascals (MPa), or a total pressure of 1.6 trillion times the intense conditions found deep beneath Earth's crust. This marks the highest pressure ever recorded in a sheared-flow-stabilized Z p ...

--- Sample 2 ---
Detecting infrared light is critical in an enormous range of technologies, from remote controls to autofocus systems to self-driving cars and virtual reality headsets. That means there would be major benefits from improving the efficiency of infrared sensors, such as photodiodes. ...

===== BATCH 207/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 67
Generate min_length: 23

--- Sample 1 ---
Scientists discovered that the Great Oxidation Event, 2.1 to 2.4 billion years ago, wiped out early cyanobacteria, leaving Earth’s air oxygen-free for hundreds of millions of years. By mimicking the Archean Earth, they discovered that nickel and urea—commonly found on Earth ...

--- Sample 2 ---
Researchers have gained a new understanding of how the brain processes reward and risk information. A study shows how nerve cells in the so-called Amygdala not only encode the probability and magnitude of rewards, but also dynamically process this information to predict value and risk. The findings  ...

===== BATCH 208/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 28

--- Sample 1 ---
A team of scientists has elucidated an ancient mechanism of cellular respiration. To that end, they studied bacteria that feed on the gases carbon dioxide and hydrogen, and turn them into acetic acid -- a metabolic pathway that emerged very early in evolution. The international team has now been abl ...

--- Sample 2 ---
Sustainably produced, biodegradable materials are an important focus of modern materials science. However, when working natural materials such as cellulose, lignin or chitin, researchers face a trade-off. Although these substances are biodesgradable in their pure form, they are often not ideal when  ...

===== BATCH 209/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 132
Generate min_length: 46

--- Sample 1 ---
Clothes that can mimic the feeling of being touched, touch displays that provide haptic feedback to users, or even ultralight loudspeakers. These are just some of the devices made possible using thin silicone films that can be precisely controlled so that they vibrate, flex, press or pull exactly as ...

--- Sample 2 ---
Climate interventions are accelerating in our oceans, but without responsible governance, they could do more harm than good. New research shows that coral bleaching, rising sea levels, and biodiversity loss are no longer distant threats — they are unfolding now, with profound consequences for marine ...

===== BATCH 210/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 46
Generate min_length: 16

--- Sample 1 ---
Companies should avoid scheduling important work tasks immediately following an election, according to a new study. ...

--- Sample 2 ---
People are more comfortable talking to female rather than male robots working in service roles in hotels, according to a new study. ...

===== BATCH 211/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 80
Generate min_length: 28

--- Sample 1 ---
A study has used advanced genetic and genomic techniques to offer a major step forward in understanding and diagnosing infectious intestinal diseases. The large-scale study analyzed more than 1,000 stool samples from people with diarrhoeal illness to harness two cutting edge tools. ...

--- Sample 2 ---
Friendship comes with complex pros and cons -- possibly explaining why some individuals are less sociable, according to a new study of gorillas. ...

===== BATCH 212/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 63
Generate min_length: 22

--- Sample 1 ---
Scientists have created a new form of germanium that can act as superconductors, allowing electric currents to circulate endlessly without losing energy. This breakthrough could accelerate the development of next-generation quantum devices. ...

--- Sample 2 ---
Lifestyle and health factors that are linked with heart disease appear to have a greater impact on cardiovascular risk in women than men, according to a new study. ...

===== BATCH 213/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 56
Generate min_length: 19

--- Sample 1 ---
Researchers have used the chemical fingerprints of zinc contained in meteorites to determine the origin of volatile elements on Earth. The results suggest that without 'unmelted' asteroids, there may not have been enough of these compounds on Earth for life to emerge. ...

--- Sample 2 ---
Researchers found that a retrovirus-derived genetic element or 'retrotransposon' is essential for myelin production in mammals, amphibians, and fish. The gene sequence, which they dubbed 'RetroMyelin,' is likely a result of ancient ...

===== BATCH 214/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 70
Generate min_length: 24

--- Sample 1 ---
In the parable of the blind men and the elephant, several blind men each describe a different part of an elephant they are touching -- a sharp tusk, a flexible trunk, or a broad leg -- and disagree about the animal's true nature. The story illustrates the problem of understanding an unseen, or laten ...

--- Sample 2 ---
Harvard scientists have uncovered the chemical mechanism by which certain salt compounds break down protein waste, like wool and feathers, in the presence of certain compounds. This breakthrough could lead to greener, more sustainable protein recycling. ...

===== BATCH 215/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 37
Generate min_length: 12

--- Sample 1 ---
How do rogue planetary-mass objects -- celestial bodies with masses between stars and planets -- form? An international team of astronomers has used advanced simulations to show that these enigmatic objects ...

--- Sample 2 ---
People's preference for simple explanations of any situation is connected to their desire to execute tasks efficiently, finds a new study. ...

===== BATCH 216/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 114
Generate min_length: 39

--- Sample 1 ---
MIT’s CHIME telescope has detected a near- and ultrabright fast radio burst 130 million light-years away in the Ursa Major constellation, offering scientists the clearest look yet at FRBs and the environments from which they emerge. This ultrafast signal, nicknamed RBFLOAT, is one of the brightest r ...

--- Sample 2 ---
Engineers have engineered bacterial signals from as far as 90 meters away. Their work could lead to the development of bacterial sensors for agricultural and other applications, which could be monitored by drones or satellites. ...

===== BATCH 217/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 72
Generate min_length: 25

--- Sample 1 ---
Boys are good at math, girls not so much? A study has analyzed the social mechanisms that contribute to the gender gap in math confidence. While peer comparisons seem to play a crucial role for boys, girls' subjective evaluations are more likely to be based on objective performance. ...

--- Sample 2 ---
Researchers at ETH Zurich have produced over 400 different types of nerve cells from stem cells in the lab, far surpassing previous efforts for producing only a few dozen. By using genetic engineering and specialized morphogens, they achieved almost 200 different conditions, including Alzheimer’s an ...

===== BATCH 218/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 114
Generate min_length: 39

--- Sample 1 ---
Researchers have identified a never-before-seen mechanism that enables the human immunodeficiency type 1 virus (HIV-1) to evade the body's natural defenses and use it to support its survival and replication. ...

--- Sample 2 ---
Climate scientists reveal that millions of today's young people will live through unprecedented lifetime exposure to heatwaves, crop failures, river floods, droughts, wildfires and tropical storms under current climate policies. ...

===== BATCH 219/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 38
Generate min_length: 13

--- Sample 1 ---
Drastic declines in biodiversity due to human activities present risks to understanding animal behaviors such as tool use, according to researchers. Shrinking animal populations make the study of these behaviors ...

--- Sample 2 ---
Language comprehension changes hemisphere specialization, but production does not, according to new research. ...

===== BATCH 220/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 61
Generate min_length: 21

--- Sample 1 ---
A longer paternity leave after the birth of a child can improve the co-parenting relationship between moms and dads in a key way. ...

--- Sample 2 ---
Are we putting our faith in technology that we don't fully understand? A new study comes at a time when AI systems are making decisions impacting our daily lives -- from banking and healthcare to crime detection. The study calls for an immediate shift in how AI models are designed and evaluated, emp ...

===== BATCH 221/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 68
Generate min_length: 23

--- Sample 1 ---
Immersing in virtual reality nature scenes helped relieve symptoms that are often seen in people living with long-term pain, with those who felt more present experiencing the strongest effects. ...

--- Sample 2 ---
Diamond quantum sensors can be used to analyze the magnetization response of soft magnetic materials used in power electronics; report scientists based on collaborative research. Using a novel imaging technique, they developed quantum protocols to simultaneously image both the amplitude and phase of ...

===== BATCH 222/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 28

--- Sample 1 ---
A new study examined whether a specialized diet could improve symptoms of gastrointestinal disorders linked to an imbalance in gut microbiota. The research tested the elemental diet's effectiveness and explored whether improving its unappealing taste -- a major barrier -- could help patients adhere  ...

--- Sample 2 ---
In the past two years, the Food and Drug Administration has approved two novel Alzheimer's therapies, based on data from clinical trials showing that both drugs slowed the progression of the disease. But while the approvals of lecanemab and donanemab, both antibody therapies that clear plaque-causin ...

===== BATCH 223/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 81
Generate min_length: 28

--- Sample 1 ---
Determining how strong your drink is doesn't need to be either guesswork or lab work. New research has made it as simple as checking your messages -- and more colorful, too. Researchers have developed a smartphone-compatible ethanol sensor that can visually detect a full range of ethanol concentrati ...

--- Sample 2 ---
A researcher's recent work on dyslexia has unexpectedly produced a startling discovery which clearly demonstrates how the cooperative areas of the brain responsible for reading skill are also at work during unrelated activities, such as multiplication. ...

===== BATCH 224/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 50
Generate min_length: 17

--- Sample 1 ---
A research team has successfully developed a super-photostable organic dye after two years of dedicated research -- demonstrating perseverance akin to that of Marie Curie, who painstakingly extracted just 0.1 grams of radium from eight tons ...

--- Sample 2 ---
Female hormones can suppress pain by making immune cells near the spinal cord produce opioids, a new study has found. This stops pain signals before they get to the brain. ...

===== BATCH 225/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 79
Generate min_length: 27

--- Sample 1 ---
Researchers have achieved a new material that will be pivotal in making the next generation of high-power electronics faster, transparent and more efficient. This artificially designed material allows electrons to move faster while remaining transparent to both visible and ultraviolet light, breakin ...

--- Sample 2 ---
Singing to your infant can significantly boost the baby's mood, according to a recent study. Around the world and across cultures, singing to babies seems to come instinctively to caregivers. Now, new findings support that singing is an easy, safe, and free way to help improve the mental well-being  ...

===== BATCH 226/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 87
Generate min_length: 30

--- Sample 1 ---
Nearly 3 out of every 4 older Americans have experienced at least one extreme weather event in the last two years, a new poll finds. And living through such an event appears to make a big difference in how they view the potential impact of climate change on their health. ...

--- Sample 2 ---
A new study found that about 6% of pregnant women reported using marijuana during the last month, and many did not associate it with health risks. The study highlights the importance of education surrounding marijuana use during pregnancy. ...

===== BATCH 227/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 85
Generate min_length: 29

--- Sample 1 ---
Whales are not just big, they're a big deal for healthy oceans. When they poop, whales move tons of nutrients from deep water to the surface. Now new research shows that whales also move tons -- nutrients thousands of miles -- in their urine. ...

--- Sample 2 ---
A collaboration has hit the trifecta of sustainability technology: The group has developed a low-cost method to produce carbon-free 'green' hydrogen via solar-powered electrolysis of seawater. A happy byproduct of the process? Potable water. ...

===== BATCH 228/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 99
Generate min_length: 34

--- Sample 1 ---
If the experience of watching a FIFA World Cup soccer final is intense, spare a thought for the players, who are competing at an ever increasing intensity, according to a new study. ...

--- Sample 2 ---
While thousands of planets have been discovered around other stars, relatively little is known about them. A NASA catalog featuring 126 exotic, newly discovered worlds includes detailed measurements that allow for comparisons with our own solar system. ...

===== BATCH 229/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 78
Generate min_length: 27

--- Sample 1 ---
Scientists have uncovered evidence that Denisovans mixed with early humans multiple times, passing on genes for survival in harsh environments, from the Himalayas to the Arctic. Genetic analysis of a finger bone found in Denisova Cave in the Altai Mountains of Siberia revealed it came from a previou ...

--- Sample 2 ---
You've got a full hour until your next meeting. But you probably won't make the most of that time, new research suggests. Researchers found that free time seems shorter to people when it comes before a task or appointment on their calendar. ...

===== BATCH 230/616 =====
Input size: 2
Max tokenized length: 512
Generate max_length: 46
Generate min_length: 16

--- Sample 1 ---

In [ ]:
metrics = evaluate_summaries(
    refs=test_df["abstract"].astype(str).tolist(),
    preds=test_df["fine_tune_bart_summary"].tolist()
)

print("\n=========== FINAL METRICS ===========")
for k, v in metrics.items():
    print(f"{k}: {v:.4f}")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

=========== FINAL METRICS ===========
ROUGE-1: 60.2872
ROUGE-2: 47.7084
ROUGE-L: 53.9225
BERTScore: 92.9393

# Factual consistency

In [ ]:
from transformers import pipeline
import torch

nli = pipeline(
    "text-classification",
    model="roberta-large-mnli",
    return_all_scores=False,
    device=0 if torch.cuda.is_available() else -1
)

config.json:   0%|          | 0.00/688 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.43G [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cuda:0
/usr/local/lib/python3.12/dist-packages/transformers/pipelines/text_classification.py:111: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [ ]:
def factual_consistency_score(inputs, summaries, max_chars=600):
    labels = []
    scores = []

    for inp, summ in zip(inputs, summaries):
        if not summ or not inp:
            labels.append("EMPTY")
            scores.append(0.0)
            continue

        premise = inp[:max_chars]
        hypothesis = summ

        try:
            result = nli({
                "text": premise,
                "text_pair": hypothesis
            })

            if isinstance(result, list):
                result = result[0]

            labels.append(result["label"])
            scores.append(result["score"])

        except Exception as e:
            print("NLI ERROR:", repr(e))
            labels.append("ERROR")
            scores.append(0.0)

    return labels, scores

In [ ]:
print(nli({
    "text": test_df["full_story"].iloc[0][:600],
    "text_pair": test_df["bart_summary"].iloc[0]
}))

{'label': 'NEUTRAL', 'score': 0.491384357213974}

In [ ]:
labels_base, scores_base = factual_consistency_score(
    test_df["full_story"].tolist(),
    test_df["bart_summary"].tolist()
)

labels_ft, scores_ft = factual_consistency_score(
    test_df["full_story"].tolist(),
    test_df["fine_tune_bart_summary"].tolist()
)

test_df["nli_base"] = labels_base
test_df["nli_ft"] = labels_ft

In [ ]:
print("BART-base NLI:")
print(test_df["nli_base"].value_counts(normalize=True) * 100)

print("\nFine-tuned BART NLI:")
print(test_df["nli_ft"].value_counts(normalize=True) * 100)

BART-base NLI:
nli_base
NEUTRAL          60.714286
ENTAILMENT       37.824675
CONTRADICTION     1.461039
Name: proportion, dtype: float64

Fine-tuned BART NLI:
nli_ft
NEUTRAL          73.376623
ENTAILMENT       25.324675
CONTRADICTION     1.298701
Name: proportion, dtype: float64

# Compression & Coverage

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [ ]:
import nltk
nltk.download("punkt")

from nltk.util import ngrams

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
def compression_ratio(input_text, summary):
    if not input_text or not summary:
        return 0.0
    return len(summary.split()) / max(len(input_text.split()), 1)

In [ ]:
def coverage(input_text, summary):
    if not input_text or not summary:
        return 0.0

    input_words = set(input_text.lower().split())
    summary_words = summary.lower().split()

    return sum(w in input_words for w in summary_words) / len(summary_words)

In [ ]:
def redundancy(summary, n=3):
    if not summary:
        return 0.0

    tokens = summary.split()
    if len(tokens) < n:
        return 0.0

    ng = list(ngrams(tokens, n))
    return 1 - len(set(ng)) / len(ng)

In [ ]:
def analyze_style(df, col):
    return {
        "compression": df.apply(
            lambda x: compression_ratio(x["full_story"], x[col]), axis=1
        ).mean(),
        "coverage": df.apply(
            lambda x: coverage(x["full_story"], x[col]), axis=1
        ).mean(),
        "redundancy": df[col].apply(redundancy).mean()
    }

style_base = analyze_style(test_df, "bart_summary")
style_ft = analyze_style(test_df, "fine_tune_bart_summary")

print("BART-base:", style_base)
print("Fine-tuned:", style_ft)
def analyze_style(df, col):
    return {
        "compression": df.apply(
            lambda x: compression_ratio(x["full_story"], x[col]), axis=1
        ).mean(),
        "coverage": df.apply(
            lambda x: coverage(x["full_story"], x[col]), axis=1
        ).mean(),
        "redundancy": df[col].apply(redundancy).mean()
    }

style_base = analyze_style(test_df, "bart_summary")
style_ft = analyze_style(test_df, "fine_tune_bart_summary")

print("BART-base:", style_base)
print("Fine-tuned:", style_ft)

BART-base: {'compression': np.float64(0.08734836606809604), 'coverage': np.float64(0.9712237671991447), 'redundancy': np.float64(0.0002247580708683902)}
Fine-tuned: {'compression': np.float64(0.06795510018286195), 'coverage': np.float64(0.9497975030839589), 'redundancy': np.float64(0.0)}
BART-base: {'compression': np.float64(0.08734836606809604), 'coverage': np.float64(0.9712237671991447), 'redundancy': np.float64(0.0002247580708683902)}
Fine-tuned: {'compression': np.float64(0.06795510018286195), 'coverage': np.float64(0.9497975030839589), 'redundancy': np.float64(0.0)}

Nhận xét:
- Kết quả phân tích cho thấy mô hình BART sau khi fine-tune tạo ra các bản tóm tắt ngắn gọn hơn và ít lặp ý hơn so với mô hình BART-base ban đầu. Mặc dù độ bao phủ nội dung của mô hình fine-tuned giảm nhẹ, giá trị này vẫn ở mức cao, cho thấy mô hình không bịa thông tin mà có xu hướng trừu tượng hóa nội dung tốt hơn. Tuy nhiên, tỷ lệ nén thấp cũng cho thấy nguy cơ mô hình bỏ sót một số chi tiết quan trọng trong các văn bản dài.

# Test Model

In [ ]:
def show_abstract_comparisons(df, ref_col, pred_col, n=20):
    for i in range(min(n, len(df))):
        print(f"\n SAMPLE {i+1}")

        print(" ORIGINAL ABSTRACT:")
        print(df.loc[i, ref_col])

        print("\n GENERATED ABSTRACT (Fine-tuned BART):")
        print(df.loc[i, pred_col])

In [ ]:
show_abstract_comparisons(
    df=test_df,
    ref_col="abstract",
    pred_col="fine_tune_bart_summary",
    n=20
)

 SAMPLE 1
 ORIGINAL ABSTRACT:
Researchers identified over 400 genes tied to various forms of frailty, offering fresh insight into why people age differently. The study highlights six distinct pathways of unhealthy aging, opening the door to more precise, targeted anti-aging interventions.

 GENERATED ABSTRACT (Fine-tuned BART):
Scientists have uncovered 400 genes linked to different forms of unhealthy aging, shedding light on why some people thrive into their 90s while others struggle decades earlier. The study reveals that different groups of genes underlie different kinds of disordered aging, a.k.a. frailty, ranging from cognitive decline to mobility issues to social

 SAMPLE 2
 ORIGINAL ABSTRACT:
Life evolved from simple geochemical processes present on the early Earth. However, the details of this transformation remain a mystery. In this study, researchers modeled the emergence of metabolic pathways from simple geochemical precursors and concluded that surprisingly few reactions in the history of metabolism may have been lost to time.

 GENERATED ABSTRACT (Fine-tuned BART):
If the history of biochemistry is rife with forgotten reactions, would there be any way to tell? Researchers reasoned that forgotten chemistry would appear as discontinuities or 'breaks' in the path that chemistry takes from simple geochemical molecules to complex biological molecules.

 SAMPLE 3
 ORIGINAL ABSTRACT:
A study reveals that inflammation associated with Marfan syndrome increases vulnerability to neurological diseases and complications following strokes, as demonstrated in animal models.

 GENERATED ABSTRACT (Fine-tuned BART):
A study reveals that inflammation associated with Marfan syndrome increases vulnerability to neurological diseases and complications following strokes, as demonstrated in animal models.

 SAMPLE 4
 ORIGINAL ABSTRACT:
A research team has found that telemedicine may help to reduce the use of low-value tests.

 GENERATED ABSTRACT (Fine-tuned BART):
Low-value care -- medical tests and procedures that provide little to no benefit to patients -- contributes to excess medical spending and both direct and cascading harms to patients. A research team has found that

 SAMPLE 5
 ORIGINAL ABSTRACT:
Scientists have cracked a century-old physics mystery by detecting magnetic signals in non-magnetic metals using only light and a revamped laser technique. Previously undetectable, these faint magnetic “whispers” are now measurable, revealing hidden patterns of electron behavior. The breakthrough could revolutionize how we explore magnetism in everyday materials—without bulky instruments or wires—and may open new doors for quantum computing, memory storage, and advanced electronics.

 GENERATED ABSTRACT (Fine-tuned BART):
Researchers have finally “heard” the faint magnetic signals from metals like copper and gold—something that had eluded science since the 1800s. Using just a blue laser and smart modulation, they found a way to “see” these invisible signals without needing a microphone. This breakthrough could revolutionize how we understand and understand magnetic fields.

 SAMPLE 6
 ORIGINAL ABSTRACT:
New research shows that poor sleep could make the brain appear years older than it really is. Using MRI scans and machine learning, scientists found a clear link between unhealthy sleep patterns and accelerated brain aging.

 GENERATED ABSTRACT (Fine-tuned BART):
People who sleep poorly are more likely than others to have brains that appear older than they actually are. A massive study of over 27,500 middle-aged and older people found that low inflammation in the body could explain just over ten per cent of the link between poor sleep and accelerated brain aging.

 SAMPLE 7
 ORIGINAL ABSTRACT:
Does our ability to enjoy music have a biological basis? A genetic twin study shows that music enjoyment is partly heritable. Scientists uncovered genetic factors that influence the degree of music enjoyment, which were partly distinct from genes influencing general enjoyment of rewarding experiences or musical ability.

 GENERATED ABSTRACT (Fine-tuned BART):
Music is central to human emotion and culture. Does our ability to enjoy music have a biological basis? A genetic twin study shows that music enjoyment is partly heritable. Scientists uncovered genetic factors that

 SAMPLE 8
 ORIGINAL ABSTRACT:
In a recent study, researchers systematically tested an early version of ChatGPT's understanding of statements in six categories: facts, conspiracies, controversies, misconceptions, stereotypes, and fiction.

 GENERATED ABSTRACT (Fine-tuned BART):
New research into large language models shows that they repeat conspiracy theories, harmful stereotypes, and other forms of misinformation.

 SAMPLE 9
 ORIGINAL ABSTRACT:
Scientists have uncovered a startling metabolic twist: mice engineered to lack the amino acid cysteine, and fed a cysteine-free diet, shed nearly a third of their body weight in just a week. The deprivation caused energy pathways to collapse, forcing fat to burn away at a furious pace while vital molecules like coenzyme A dwindled. This set off a cascade of stress responses usually seen only in cancer cells, while also preventing fat stores from being rebuilt.

 GENERATED ABSTRACT (Fine-tuned BART):
Mice engineered to lack the ability to make the amino acid cysteine lost 30% of their body weight in just one week, largely due to a malfunctioning small molecule called coenzyme A. Lower levels of this molecule caused the animals to rapidly burn fat, activating metabolic pathways that slowed metabolism and activated stress responses. The findings hint at a powerful new direction for weight loss

 SAMPLE 10
 ORIGINAL ABSTRACT:
Researchers at NYU Langone Health discovered that cutting off blood flow accelerates cancer growth by prematurely aging the bone marrow and weakening the immune system. In mouse models, restricted blood flow doubled the growth rate of breast tumors, mimicking changes seen during aging. The study found that ischemia reprograms bone marrow stem cells, skewing the immune system toward cells that suppress rather than fight cancer.

 GENERATED ABSTRACT (Fine-tuned BART):
Cutting off blood flow in the legs can prematurely age the bone marrow, weakening the immune system’s ability to fight cancer. Researchers found that blocked blood flow caused breast tumors to grow at double the rate seen in mice without restricted flow, mirroring changes seen with aging.

 SAMPLE 11
 ORIGINAL ABSTRACT:
Researchers have analyzed ancient DNA from Borrelia recurrentis, a type of bacteria that causes relapsing fever, pinpointing when it evolved to spread through lice rather than ticks, and how it gained and lost genes in the process.

 GENERATED ABSTRACT (Fine-tuned BART):
Researchers have analyzed ancient DNA from Borrelia recurrentis, a type of bacteria that causes relapsing fever, pinpointing when it evolved to spread through lice rather than ticks, and how it gained and lost genes in the process.

 SAMPLE 12
 ORIGINAL ABSTRACT:
Scientists point out that a coherent approach to understanding the threats posed by artificial intelligence is still elusive. They call for a complex systems perspective to better assess and mitigate these risks, particularly in light of long-term uncertainties and complex interactions between AI and society.

 GENERATED ABSTRACT (Fine-tuned BART):
Scientists point out that a coherent approach to understanding these threats is still elusive. They call for a complex systems perspective to better assess and mitigate these risks, particularly in light of long-term uncertainties and complex interactions between A.I. and society.

 SAMPLE 13
 ORIGINAL ABSTRACT:
Labeling the credibility of information sources does not shift the consumption of news away from low-quality sources or reduce belief in widely circulated inaccurate claims among average internet users, but providing an indicator of sources' quality may improve the news diet quality of the heaviest consumers of misinformation.

 GENERATED ABSTRACT (Fine-tuned BART):
Labeling the credibility of information sources does not shift the consumption of news away from low-quality sources or reduce belief in widely circulated inaccurate claims among average internet users, but providing an indicator of sources' quality may improve the news diet quality of the heaviest consumers of misinformation, shows a new study. Notably, the researchers also found that a majority of people rely on

 SAMPLE 14
 ORIGINAL ABSTRACT:
As rising global temperatures alter ecosystems worldwide, animal species usually have two choices: adapt to changing local conditions or flee to a cooler clime. Ecologists have long assumed that the world's bird species were best equipped to respond to the pressures of climate change simply because they have the option of flying to higher altitudes or towards global poles. But a new study finds that few bird species are able to escape the realities of a warming world.

 GENERATED ABSTRACT (Fine-tuned BART):
As rising global temperatures alter ecosystems worldwide, animal species usually have two choices: adapt to changing local conditions or flee to a cooler clime. Ecologists have long assumed that the world's bird species were best equipped to respond to the pressures of climate change simply because they have the option of flying to higher altitudes or towards global poles. But a new study finds that

 SAMPLE 15
 ORIGINAL ABSTRACT:
Long-term inhalation of toxic air appears to dull the protective power of regular workouts, according to a massive global study spanning more than a decade and over a million adults. While exercise still helps people live longer, its benefits shrink dramatically in regions with heavy fine particle pollution—especially above key PM2.5 thresholds common in many parts of the world. The researchers emphasize that outdoor activity shouldn’t stop, but better air quality could unlock far greater health gains.

 GENERATED ABSTRACT (Fine-tuned BART):
Long-term inhalation of toxic air appears to dull the protective power of regular workouts, according to a massive global study spanning more than a decade and over a million adults. While exercise still helps people live longer, its benefits shrink dramatically in regions with heavy fine particle pollution—especially above key PM2.5

 SAMPLE 16
 ORIGINAL ABSTRACT:
While astronomers have taken about two dozen zoomed-in images of stars in our galaxy, unveiling their properties, countless other stars dwell within other galaxies, so far away that observing even one of them in detail has been extremely challenging. Up until now.

 GENERATED ABSTRACT (Fine-tuned BART):
Astrophysicists have succeeded in taking a zoomed-in image of a dying star in a galaxy outside our own Milky Way. Located a staggering 160 000 light-years from us, the star WOH G64 was imaged thanks to the impressive sharpness offered by the European Southern Observatory's Very

 SAMPLE 17
 ORIGINAL ABSTRACT:
People have assumed climate change solutions that sequester carbon from the air into soils will also benefit crop yields. But a new study finds that most regenerative farming practices to build soil organic carbon -- such as planting cover crops, leaving stems and leaves on the ground and not tilling -- actually reduce yields in many situations.

 GENERATED ABSTRACT (Fine-tuned BART):
People have assumed climate change solutions that sequester carbon from the air into soils will also benefit crop yields. But a new study finds that most regenerative farming practices to build soil organic carbon -- such as planting cover crops, leaving stems and leaves on the ground and not tilling -- actually reduce yields in

 SAMPLE 18
 ORIGINAL ABSTRACT:
Parents should be taught how to better understand the increasingly volatile social media landscape that is deploying sophisticated algorithms, according to a new study.

 GENERATED ABSTRACT (Fine-tuned BART):
Parents should be taught how to better understand the increasingly volatile social media landscape that is deploying sophisticated algorithms, according to a new study.

 SAMPLE 19
 ORIGINAL ABSTRACT:
Many people struggle to maintain a healthy weight, and choosing the optimal meals for weight loss can be challenging. A research team has developed a weight management program that helps individuals plan meals with the assistance of a web application and support from a registered dietitian. In a new study, they discuss the app's features, development, and implementation.

 GENERATED ABSTRACT (Fine-tuned BART):
A research team has developed a weight management program that helps individuals plan meals with the assistance of a web application and support from a registered dietitian. In a new study, they discuss the app's features, development, and implementation.

 SAMPLE 20
 ORIGINAL ABSTRACT:
People who are dogmatic about their views seek less information and make less accurate judgements as a result, even on simple matters unrelated to politics, according to a new study.

 GENERATED ABSTRACT (Fine-tuned BART):
People who are dogmatic about their views seek less information and make less accurate judgements as a result, even on simple matters unrelated to politics, according to a new study.

In [ ]:
!cp -r ./bart_finetuned/checkpoint-7000 /content/drive/MyDrive/